In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.linear_model import LinearRegression 
import warnings
warnings.filterwarnings('ignore',category=FutureWarning)
warnings.filterwarnings('ignore')

In [4]:
df=pd.read_csv(r"C:\Users\prave\OneDrive\Desktop\ML Learning\Algorithms\Supervised Learning\Linear Regression\Single linear regression\houseprices.csv")
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [5]:
x_df = df.drop('price',axis=1)
x_df

area
0  2600
1  3000
2  3200
3  3600
4  4000

In [6]:
y_df = df.drop('area',axis=1)
y_df

price
0  550000
1  565000
2  610000
3  680000
4  725000

In [7]:
lr=LinearRegression()
lr.fit(x_df,y_df)

LinearRegression()

In [8]:
lr.coef_

array([[135.78767123]])

In [9]:
lr.intercept_

array([180616.43835616])

#pickle file is used to save the model for sharing

#any other formats for ML may not work

pickle file gives always binary output

In [10]:
import pickle

In [11]:
# writing file as binary file, uses wb
with open('lr_model','wb') as file: 
    pickle.dump(lr,file)

opening the model shared using pickle

In [12]:
with open('lr_model','rb') as file1:
    pic = pickle.load(file1)


In [13]:
pic.coef_

array([[135.78767123]])

In [14]:
pic.intercept_

array([180616.43835616])

In [18]:
pic.predict([[45000]])

array([[6291061.64383562]])

In [16]:
# ### # create a json file with some data

import json

sampleJson={
    'name':'Praveen',
    'place':'Pala',
    'Phone':'9495036485'
    }

json_object = json.dumps(sampleJson)

In [17]:
with open('sample.json','w') as file2:
    file2.write(json_object)

In [19]:
with open('sample.json','r') as readfile3:
    readfile3 = json.load(readfile3)

Saving Trained model using Joblib

joblib is used for saving ml models 

In [20]:
import joblib

In [21]:
joblib.dump(lr,'lr_model_joblib')

['lr_model_joblib']

In [22]:
model=joblib.load('lr_model_joblib')

In [23]:
model.coef_

array([[135.78767123]])

In [24]:
model.intercept_

array([180616.43835616])

In [25]:
model.predict([[6400]])

array([[1049657.53424658]])