In [1]:
#install python package-Numpy. the number inside In[] shows how many times run has worked

In [2]:
#pip install numpy

In [3]:
import numpy as np  # calling numpy #number inside In[] changed to 1 since kernal was restarted

In [4]:
#esc to come out of the editing
#enter to come inside the editing from blue to green

In [5]:
mylist=[1,2,5,9,7,8,6]

In [6]:
print(mylist)

[1, 2, 5, 9, 7, 8, 6]


In [8]:
mylist1=[1,0.3,False]

In [10]:
arr=np.array(mylist1)
arr
arr.dtype

dtype('float64')

In [7]:
#dir(np)

In [8]:
#help(np) or shift+tab

In [9]:
arr=np.array(mylist)

In [10]:
print(arr)

[1 2 5 9 7 8 6]


In [11]:
print(type(arr))

<class 'numpy.ndarray'>


In [12]:
arr.size

7

In [13]:
arr.shape

(7,)

In [14]:
my_list1=[1,2,5,9] # will give a 3x4 array
my_list2=[5,9,7,8]
my_list3=[9,7,8,6]

arr=np.array([my_list1,my_list2,my_list3]) # is given to take up the array as 3 list since default is 1

In [15]:
arr  # 2 [[]] gives the idea that it is 2D array. 

array([[1, 2, 5, 9],
       [5, 9, 7, 8],
       [9, 7, 8, 6]])

In [16]:
type(arr)

numpy.ndarray

In [17]:
arr.size

12

In [18]:
arr.shape

(3, 4)

In [19]:
# numpy array indexing

my_lst=[1,2,3,4,5]
arr=np.array(my_lst)

In [20]:
arr

array([1, 2, 3, 4, 5])

In [21]:
print(arr[0])

1


In [22]:
print("the 2nd element is :",arr[1])
print("the 3rd element:",arr[2]," and the 4th is: ",arr[3])

the 2nd element is : 2
the 3rd element: 3  and the 4th is:  4


In [23]:
#access 2D array
my_list1=[1,2,3,4,5]
my_list2=[2,3,4,5,6]
my_list3=[9,7,6,8,9]

arr=np.array([my_list1,my_list2,my_list3])

In [24]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [25]:
arr[0,2]

3

In [26]:
print('2nd element in 1st row is;',arr[0,1])

2nd element in 1st row is; 2


In [27]:
print('2nd row 5th element',arr[1,4])

2nd row 5th element 6


In [28]:
Arr=np.array([[1,2,3],[4,5,6]])

In [29]:
Arr

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
print('value of array : ',Arr,'\n')
print('shape of array: ',Arr.shape,'\n')
print('size of array: ',Arr.size,'\n')
print('1st row 1st element: ',Arr[0,0],'\n')
print('2nd row 3rd element: ',Arr[1,2],'\n')

value of array :  [[1 2 3]
 [4 5 6]] 

shape of array:  (2, 3) 

size of array:  6 

1st row 1st element:  1 

2nd row 3rd element:  6 



In [31]:
#-ve indexing supported as in python


In [32]:
mylist=[1,2,3,4,5,6,7,8]

varr=np.array(mylist)

print(varr)

[1 2 3 4 5 6 7 8]


In [33]:
#slicing
#arr[start:end]
varr[0:5]

array([1, 2, 3, 4, 5])

In [34]:
varr[3:]

array([4, 5, 6, 7, 8])

In [35]:
varr[-3:-1]

array([6, 7])

In [36]:
varr[1::2]

array([2, 4, 6, 8])

In [37]:
# slicing 2D arrays

In [38]:
mylist1=[1,2,3,4,5]
mylist2=[2,3,4,5,6]
mylist3=[9,7,6,8,9]
array1=np.array([mylist1,mylist2,mylist3])

In [39]:
array1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [40]:
array1[1:,1:4]  # 2nd row to all the rows following and columns 2-4 (index start from 0)

array([[3, 4, 5],
       [7, 6, 8]])

In [41]:
array1[:,1:4]

array([[2, 3, 4],
       [3, 4, 5],
       [7, 6, 8]])

In [42]:
#arrange function

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [44]:
np.linspace(0,100) # creates array like normal distribution chart

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

In [111]:
np.linspace(0,100,5) # required spacing may be given

array([  0.,  25.,  50.,  75., 100.])

In [46]:
arr=np.array([1,2,3,4,5])

print(arr.dtype) #the 32 after datatype in output shows memory allocation

int32


In [47]:
ar=np.array([1.0,2.0,3.0])

print(ar.dtype)

float64


In [48]:
arr1=np.array(['apple','orange','banana','cherry'])

print(arr1.dtype)

<U6


In [49]:
arr2=np.array(['apple','orange','banana','cherry','bananacherry'])

print(arr2.dtype)   #Unicode-U

<U12


In [50]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int32


In [51]:
arr=np.array([1,2,3,4,5],dtype='S')# changing datatype to string
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


In [52]:
arr=np.array([1,2,3,4,5],dtype= np.int64)  # 64 bit int datatype will be incorporated
print(arr.dtype)

int64


In [53]:
arr=np.array([1,2,3,4,5],dtype=np.float32)
print(arr)
print(arr.dtype)

[1. 2. 3. 4. 5.]
float32


In [54]:
#Basic Array math
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])

In [55]:
np.add(x,y)

array([[ 6,  8],
       [10, 12]])

In [56]:
np.subtract(x,y)

array([[-4, -4],
       [-4, -4]])

In [57]:
np.multiply(x,y)

array([[ 5, 12],
       [21, 32]])

In [58]:
np.divide(x,y)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [59]:
np.floor_divide(x,y)

array([[0, 0],
       [0, 0]], dtype=int32)

In [60]:
x+y

array([[ 6,  8],
       [10, 12]])

In [61]:
x-y

array([[-4, -4],
       [-4, -4]])

In [62]:
x*y

array([[ 5, 12],
       [21, 32]])

In [63]:
x/y

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [64]:
x**y

array([[    1,    64],
       [ 2187, 65536]], dtype=int32)

In [65]:
x=np.array([[1,2],[3,4]],dtype=np.float64)
y=np.array([[5,6],[7,8],[9,10]],dtype=np.float64)

In [66]:
x.shape

(2, 2)

In [67]:
y.shape

(3, 2)

In [68]:
#x+y #(due to shape of matrix adding subtracting and all gives error. For multiplication (nXm)*(mXp)--(nXp))

In [69]:
np.log(x)

array([[0.        , 0.69314718],
       [1.09861229, 1.38629436]])

In [70]:
np.exp(x)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [71]:
np.log10(x)

array([[0.        , 0.30103   ],
       [0.47712125, 0.60205999]])

In [72]:
np.cos(x)

array([[ 0.54030231, -0.41614684],
       [-0.9899925 , -0.65364362]])

In [73]:
np.tan(x)

array([[ 1.55740772, -2.18503986],
       [-0.14254654,  1.15782128]])

In [74]:
#floor,Ceil,Round
x=np.array([[1.5,2.5],[3.1,4.9]],dtype=np.float64)

In [75]:
np.floor(x)

array([[1., 2.],
       [3., 4.]])

In [76]:
np.ceil(x) # goes to next whole number

array([[2., 3.],
       [4., 5.]])

In [77]:
np.round(x) # goes to the nearest whole number


array([[2., 2.],
       [3., 5.]])

In [78]:
import numpy as np
x=np.array([[1,2],[3,4],[5,6]],dtype=np.float64)
y=np.array([[5,6],[7,8]],dtype=np.float64)

v=np.array([9,10],dtype=np.float64)
w=np.array([10,12.9],dtype=np.float64)

In [79]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [80]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [81]:
np.sum(x)

45

In [82]:
np.sum(x,axis=0) #column vice

array([12, 15, 18])

In [83]:
np.sum(x,axis=1) #row vice

array([ 6, 15, 24])

In [84]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [85]:
x.T #transpose


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [86]:
np.dot(w,v)

219.0

In [87]:
#numpy array copy as view
arr=np.array([1,2,3,4,5])
x=arr.copy()#The copy SHOULD NOT be affected by the changes made to the original array.

In [88]:
print(arr)

[1 2 3 4 5]


In [89]:
print(x)

[1 2 3 4 5]


In [90]:
arr[0]=100

In [91]:
print(arr)

[100   2   3   4   5]


In [92]:
print(x)

[1 2 3 4 5]


In [93]:
arr=np.array([1,2,3,4,5])
x=arr.view() #The view SHOULD be affected by the changes made to the original array.

In [94]:
arr[0]*100

100

In [95]:
x[1]=200

In [96]:
print(arr)

[  1 200   3   4   5]


In [97]:
#numpy array reshaping
arr=np.arange(1,13)
arr.shape

(12,)

In [98]:
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [99]:
print(x)

[  1 200   3   4   5]


In [100]:
arr_new= arr.reshape(3,4)

In [101]:
print(arr_new)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [102]:
#flatening array
#2D------1D
arr_new.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [103]:
#iterating an array
arr=np.arange(1,7).reshape(3,2)

In [104]:
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [105]:
for i in arr:
    print(i)

[1 2]
[3 4]
[5 6]


In [106]:
#joining numpy array
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])


In [107]:
np.concatenate((arr1,arr2))

array([1, 2, 3, 4, 5, 6])

In [11]:
#2D concatenation
arr3=np.array([[1,2],[3,4]])
arr4=np.array([[4,5],[6,7]])
np.concatenate((arr3,arr4),axis=0)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 1

In [109]:
np.concatenate((arr3,arr4),axis=1)

array([[1, 2, 4, 5],
       [3, 4, 6, 7]])